// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdaHRWL3N_xtfdDP74nHKHy6iPs1UdgYc',
    appId: '1:320089783115:web:6cc44fb3aa201dee2446ce',
    messagingSenderId: '320089783115',
    projectId: 'footware-project-be6ff',
    authDomain: 'footware-project-be6ff.firebaseapp.com',
    storageBucket: 'footware-project-be6ff.appspot.com',
    measurementId: 'G-G41EN9Y32X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPYiL4nspQ15HtA99zhHZ4LcZWwhlhy9Y',
    appId: '1:320089783115:android:aeda6ad896c456112446ce',
    messagingSenderId: '320089783115',
    projectId: 'footware-project-be6ff',
    storageBucket: 'footware-project-be6ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUti13SXV6EjyOvqcC8JArql2YXNbxXgE',
    appId: '1:320089783115:ios:99629ecc128dc7fc2446ce',
    messagingSenderId: '320089783115',
    projectId: 'footware-project-be6ff',
    storageBucket: 'footware-project-be6ff.appspot.com',
    iosBundleId: 'com.example.footwareAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUti13SXV6EjyOvqcC8JArql2YXNbxXgE',
    appId: '1:320089783115:ios:7b744d6368ec85832446ce',
    messagingSenderId: '320089783115',
    projectId: 'footware-project-be6ff',
    storageBucket: 'footware-project-be6ff.appspot.com',
    iosBundleId: 'com.example.footwareAdmin.RunnerTests',
  );
}
